en:
  errors:
    uri_has_scheme?: "has an invalid scheme (only %{list} are allowed)"
    uri_is_absolute?: "is not an absolute URL"
    uri_has_no_path?: "must not have a path"
    uri_has_no_query?: "must not have a query string"
    uri_has_no_fragment?: "must not have a fragment"
    uri_has_no_userinfo?: "must not have user info"
    directory?: "is not a directory"
